spring.datasource.url=jdbc:sqlserver://192.168.59.207:1433;databaseName=AppRedMedicronIPS_Dev;encrypt=true;trustServerCertificate=true
spring.datasource.username=DbDesarrollo
spring.datasource.password=TI.Desarrollo%*2024
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false